---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /curl-jq
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /git-server
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /network-tools
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /stirling-pdf
    schedule:
      interval: daily
