FROM docker.io/alpine:3.22.1

RUN apk add --no-cache \
        bash \
        bash-completion \
        bind-tools \
        ca-certificates \
        coreutils \
        curl \
        drill \
        file \
        findutils \
        fping \
        git \
        gping \
        ipcalc \
        iperf3 \
        iproute2 \
        iputils \
        jq \
        libidn \
        macchanger \
        masscan \
        mtr \
        neovim \
        net-tools \
        netcat-openbsd \
        nftables \
        ngrep \
        nload \
        nmap \
        nmap-nping \
        nmap-scripts \
        openssh-client \
        openssl \
        procps \
        socat \
        speedtest-cli \
        strace \
        tcpdump \
        tcptraceroute \
        termshark \
        tshark \
        vim

ENTRYPOINT ["/bin/bash"]
