---
apiVersion: v1
kind: Namespace
metadata:
  name: git

---
apiVersion: v1
kind: Pod
metadata:
  name: git-server
  namespace: git
  labels:
    app: git-server
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  containers:
    - name: git
      image: ghcr.io/yellowhat/registry/git-server:latest
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      ports:
        - name: git
          containerPort: 9418
          protocol: TCP
      startupProbe:
        tcpSocket:
          port: git
        periodSeconds: 1
        failureThreshold: 60
      readinessProbe:
        tcpSocket:
          port: git
      livenessProbe:
        tcpSocket:
          port: git
      volumeMounts:
        - name: git
          mountPath: /git
      resources:
        requests:
          memory: 16Mi
          cpu: 100m
        limits:
          memory: 128Mi
          cpu: 200m
  volumes:
    - name: git
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: git
spec:
  selector:
    app: git-server
  ports:
    - protocol: TCP
      port: 9418
      targetPort: git
