---
apiVersion: v1
kind: Pod
metadata:
  name: git-server
  namespace: default
  labels:
    app: git-server
spec:
  containers:
    - name: git
      image: ghcr.io/yellowhat/registry/git-server:latest
      ports:
        - containerPort: 9418

---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: default
spec:
  selector:
    app: git-server
  ports:
    - protocol: TCP
      port: 9418
      targetPort: 9418
