---
name: Build

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dir:
          - curl-jq
          - git-server
          - network-tools
          - pgvecto-rs
          - rpmlint
          - stirling-pdf
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Docker - Log in to registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag from Dockerfile
        run: echo "BASE_TAG=$(grep FROM Dockerfile | cut -d ':' -f 2)" >>$GITHUB_ENV
        working-directory: ${{ matrix.dir }}

      - name: Docker - Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.dir }}
          tags: |
            ${{ env.BASE_TAG }}
            latest

      - name: Docker - Build and push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          context: ${{ matrix.dir }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
