---
name: Build

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dir:
          - curl-jq
          - git-server
          - network-tools
          - podinfo
          - qbittorrent
          - smartctl-exporter
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx for multi platform builds
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker - Log in to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag from Dockerfile
        run: |
          if [ -f version.sh ]; then
              BASE_TAG=$(bash version.sh)
          else
              BASE_TAG=$(grep FROM Dockerfile | tail -1 | cut -d ':' -f 2)
          fi
          echo "BASE_TAG=$BASE_TAG" >>$GITHUB_ENV
        working-directory: ${{ matrix.dir }}

      - name: Docker - Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.dir }}
          tags: |
            ${{ env.BASE_TAG }}
            latest

      - name: Docker - Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ${{ matrix.dir }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          platforms: linux/amd64,linux/arm64
